default:
    autoload:
        '': '%paths.base%/../features/bootstrap'
    suites:
        default:
            paths: ['../features/local']
            contexts:
                - FeatureContext:
                      parameters:
                          server: "hub-cloud.browserstack.com"
                          user: "priyadineshkumar_peJNSK"
                          key: "SaHeq6qpe1T3upA6byaF"

                          capabilities:
                              build: "browserstack build 1"
                              name: "BStack local test"
                              "browserstack.debug": true
                              "browserstack.local": true
                              "browserstack.source": "behat:sample-master-v1.0"

                          environments:
                              -
                                  browser: "Chrome"
                                  os: "Windows"